[platformio]
default_envs = waveshare_2_8c_bringup

[env:waveshare_2_8c_bringup]
platform = espressif32@6.9.0
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags =
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=2
	-DBOARD_HAS_PSRAM
	-DFLIGHTDESK_HW_WAVESHARE_2_8C=1
lib_deps =
	bblanchon/ArduinoJson@^7.4.2
	bitbank2/PNGdec@^1.1.0
